name: lock
version: 0.2.2
author: Clean Team <clean@vacuumlabs.com>
description: A sample application
homepage: https://github.com/cleandart/dartlock
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: https://github.com/cleandart/dartlock
dependencies:
  logging: any
  path: '>=1.1.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.10.0'
